### ISSUE TITLE
Recomendación de Libros

### ISSUE THREAD

**Issue by elin-winter** [pdepjm/2024-tp0-presentacion-npinkas#5]
Holaa Nati, ¿qué tal? 

Me gustó mucho tu presentación, te quería preguntar nomás si tenías alguna buena recomendación de libros para hacer, siempre estoy en busca de más. Podrías hasta agregarlo en el repositorio, tu libro favorito.

**Comment by npinkas** [comment]
Hola! Te recomiendo "El Psicoanalista", de John Katzenbach. Es un thriller psicológico que a mi me gustó mucho!
Mi libro favorito diría que es Misery, ahora lo agrego a mi presentación.
