### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by luciagarcia0** [pdepjm/2024-tp0-presentacion-npinkas#6]
Hola Nati, quería sugerirte una modificación al principio del código donde dice "2024-tp0-presentacion-npinkas". Podrías editarlo como te guste, por ejemplo en el mío lo usé como título y puse mi nombre.
Saludoss

**Comment by npinkas** [comment]
Pensé que no lo podíamos modificar, ahora lo cambio. Muchas gracias!
